baseURL: https://example.org/
languageCode: en-us
title: julian.patterson
themes: ["PaperMod"]

menu:
  main:
    - identifier: blog
      name: blog
      url: /blog
      weight: 10
    - identifier: projects
      name: projects
      url: /projects
      weight: 20
    - identifier: education
      name: education
      url: /edu
      weight: 30
    - identifier: experience
      name: experience
      url: /experience
      weight: 40
    - identifier: search 
      name: search
      url: /search
      weight: 50


params:
  profileMode:
    enabled: true
    title: "Julian Patterson"
    subtitle: "As a U2 Software Engineering student minoring in Statistics, I enjoy creating software that makes a difference in people's lives. With a minor in Statistics, I aim to develop useful analytic and problem solving skills to enhance my software projects. Other than that, I enjoy running, reading, hiking, skiing and socializing. Feel free to reach out using the links below, I would love to chat!"
    imageUrl: "https://media.licdn.com/dms/image/v2/D4E03AQE0FFKJgb91Ig/profile-displayphoto-shrink_200_200/profile-displayphoto-shrink_200_200/0/1711125430731?e=1738800000&v=beta&t=R-D7kx7ZiN7-RUD4KIivNA_1wqwPOr08YH4IywatH1w" # optional
    imageTitle: " " # optional
    imageWidth: 120 # custom size
    imageHeight: 120 # custom size
    buttons:
      - name: blog
        url: "/blog"
      - name: projects
        url: "/projects"
      - name: education
        url: "/edu"
      - name: experience
        url: "/experience" 
    ShowReadingTime: true 
    ShowBreadCrumbs: true

  socialIcons: # optional 
    - name: "github"
      url: "https://github.com/julian-patterson"
    - name: "linkedin"
      url: "https://linkedin.com/in/julian-e-patterson"
    - name: "email"
      url: "mailto:julian.e.patterson@icloud.com"
    - name: "phone"
      url: "tell:514-929-1119"

  outputs:
    home:
      - HTML
      - JSON
  
