baseURL: https://julianpatterson.ca/
languageCode: en-us
title: julian.patterson
theme: "PaperMod"

outputs:
  home:
    - HTML
    - JSON

menu:
  main:
    - identifier: about
      name: about
      url: /about
      weight: 10
    - identifier: experience
      name: experience
      url: /experience
      weight: 20
    - identifier: education
      name: education
      url: /edu
      weight: 30
    - identifier: projects
      name: projects
      url: /projects
      weight: 40
    # - identifier: search
    #   name: search
    #   url: /search
    #   weight: 50

params:
  assets:
    css:
      - css/custom.css # custom CSS file
  profileMode:
    enabled: true
    title: "Julian Patterson"
    subtitle: "I am a passionate Software Engineering student driven to create impact-driven software that genuinely improves people's lives. My academic journey is enhanced by a minor in Statistics, which provides me with a strong foundation in analytical problem-solving and developing data-enhanced solutions. Outside of development, I recharge by running, hiking, and skiing, as well as connecting with new people. I'm eager to discuss new opportunities or projects—feel free to reach out using the links below, I'd love to chat!"
    imageUrl: "headshot_cropped.jpg" # optional
    imageTitle: " " # optional
    # imageWidth: 120 # custom size
    # imageHeight: 120 # custom size
    ShowReadingTime: true
    ShowBreadCrumbs: true

  socialIcons: # optional
    - name: "github"
      url: "https://github.com/julian-patterson"
    - name: "linkedin"
      url: "https://linkedin.com/in/julian-e-patterson"
    - name: "email"
      url: "mailto:julian.e.patterson@icloud.com"
    - name: "phone"
      url: "tel:514-929-1119"
